### ISSUE TITLE
Split r40 items into individual r1-r30 and r31-r40 versions

### ISSUE THREAD

**Issue by iReisen** [Paroxity/FrameHub#261]
Hey, i'd like to have the option to have rank 40 items to be split into r1-30 and 31-40

This was a feature on the mastery google spreadsheet, which was very nice because i believe that many people will get kuva/tenet weapons (aswell as the para sword and necramechs) and level them to 30 for the exp, but hold off on finishing r40 untill they are done with basically everything else. Because of this it'd be great to have this feature here available aswell since it causes quite the desync of your actual mastery exp and the exp shown on the site.

the way this would look like could simply be "Kuva Grattler (1-30)" and "Kuva Grattler (31-40)" instead of just "Kuva Grattler"

**Comment by DaPigGuy** [comment]
You can select the level for Kuva/Tenet weapons and the Paracesis by clicking the item
