### ISSUE TITLE
Venari Prime is missing in the Kavat's list.

### ISSUE THREAD

**Issue by GiulianoMarques** [Paroxity/FrameHub#266]
Venari Prime is not listed along Venari and the other Kavats.

**Comment by DaPigGuy** [comment]
Last I check, Venari Prime for whatever reason does not give mastery XP

**Comment by GiulianoMarques** [comment]
She gives, just like regular Venari. I needed 14k to L2 and after leveling Khora Prime I got the MR test prompt.

**Comment by DaPigGuy** [comment]
Ah I was not aware there was a hotfix yesterday. I've manually added Venari Prime.
