### ISSUE TITLE
Star chart mastery is incorrect

### ISSUE THREAD

**Issue by gjsmo** [Paroxity/FrameHub#267]
There are a total of 36 mastery points missing in the star chart, somewhere. I'm not sure where it is but here's a screenshot of my completed FrameHub, and a screenshot of my own mastery:

![image](https://user-images.githubusercontent.com/12057767/221763358-e6676130-8324-4cd4-a32f-7c83ea2b0a1c.png)
![image](https://user-images.githubusercontent.com/12057767/221763392-ae9ab5c8-8fdc-4318-86c3-e861faa0d5e0.png)

It looks like one mission is probably missing on both the regular star chart and Steel Path, probably the same one, worth 18 XP.

**Comment by DaPigGuy** [comment]
I did add a new node that gives 18 XP last week... 1d129aab114abfc895bbd5b3f6b4b46f4ceba15c

Make sure Tyana Pass, Mars is marked?

**Comment by gjsmo** [comment]
Interesting, for some reason that was not showing up for me despite multiple browser restarts and reboots since then. Clearing the cache fixed it though. Carry on!

**Comment by NeutronicMC** [comment]
Yep, being a single page app Framehub doesn't update until the cache is cleared or invalidated, something that we should work on solving
