### ISSUE TITLE
Add the Dorrclave melee

### ISSUE THREAD

**Issue by Ghostling225** [Paroxity/FrameHub#274]
With Abyss of Dagath, the new [Dorrclave](https://warframe.fandom.com/wiki/Dorrclave) melee was added to the game, but FrameHub doesn't feature this weapon yet.  
  
Thanks for making this awesome tool!

**Comment by DaPigGuy** [comment]
Dorrclave is already added to FrameHub, try refreshing and checking that you didn't accidentally mark it as mastered.

**Comment by Ghostling225** [comment]
Oh huh. Refreshing or relogging didn't help, but clearing site data from my browser did it. Thanks!
