### ISSUE TITLE
List forma required for Paracesis-like gear

### ISSUE THREAD

**Issue by TLATER** [Paroxity/FrameHub#275]
### Description

I'm nearing the end of my collection, and mostly just have the Kuva/Tenet weapons to level. Since each costs 5 forma to get to max, this will cost a fair bit of plat.

I'd like to know how much exactly without having to sum it up by hand - seems similar to crafting components, so it'd be cool if the site could calculate that.

### Extra Information

N/A

**Comment by DaPigGuy** [comment]
Added under the crafting components
