### ISSUE TITLE
Pop-up can hang off the page

### ISSUE THREAD

**Issue by Mulchman** [Paroxity/FrameHub#4]
Thought I'd stop spamming you on reddit and just start creating issues instead.

See the picture - the pop-up can hang off the page.

![image](https://user-images.githubusercontent.com/11757993/100029750-c18d0e00-2da6-11eb-9918-f16021eb99da.png)

**Comment by DaPigGuy** [comment]
01e63cc1bd9ec48a53e9e392329c85c261330e9b
