### ISSUE TITLE
All progress lost since checking yesterday

### ISSUE THREAD

**Issue by Mulchman** [Paroxity/FrameHub#8]
Yesterday, when I was logging issues and playing with the site, I made sure to save all my progress. Upon checking today all my progress is lost and I have to re-tick off everything I've mastered.

I'm guessing something in your update process is nuking the database? It's going to really frustrate users if you keep this up.

**Comment by NeutronicMC** [comment]
Weird, that shouldn't have happened.  The only thing I could think of that would wipe your progress is an issue with the auto save system. Let us know if you manage to get your data reset again.
