### ISSUE TITLE
Can still get pop-up to hang off the page

### ISSUE THREAD

**Issue by Mulchman** [Paroxity/FrameHub#9]
Turn on "Hide Mastered"

Spam click secondaries to say that they're mastered. At some point the positioning of the pop-up gets messed up and it'll hang off the screen.

### Browser & OS
- Browser: Google Chrome v86.0.4240.198
- Device: Windows 10

![image](https://user-images.githubusercontent.com/11757993/100138078-52fd8e00-2e42-11eb-8290-94d2785767a7.png)

**Comment by NeutronicMC** [comment]
I think I may have a fix for this. Currently it chicks if the tooltip is outside the viewport only after initial display (so if you move the mouse one pixel onto a button, it'll not perform the check).
